version: "3.4"
services:

  app:
    build:
      context: ./.docker/app
      target: dev
    volumes:
      - "./src:/var/www/html:${WEB_VOLUME_CONSISTENCY:-consistent}"
    ports:
      - "${WEB_PORT:-80}:80"
    environment:
      - HOST_UID
      - HOST_GID
      - XDEBUG_HOST
      - "XDEBUG_PORT=${XDEBUG_PORT:-9000}"

  db:
    image: mysql:5.6
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci
    environment:
      - "MYSQL_DATABASE=${DB_DATABASE}"
      - "MYSQL_ROOT_PASSWORD=${DB_PASSWORD}"
    ports:
      - "${DB_PORT:-3306}:3306"


